---
language: go

# we support the most two recent releases, and (hopefully) the tip.
go:
  - 1.5
  - 1.6
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - echo noop

script:
  - make

matrix:
  allow_failures:
    - go: tip
